absl-py==2.3.0
accelerate==1.1.0
addict==2.4.0
aiohappyeyeballs==2.6.1
aiohttp==3.12.12
aiosignal==1.3.2
albucore==0.0.24
albumentations==2.0.8
annotated-types==0.7.0
anthropic==0.55.0
anyio==4.9.0
asttokens==3.0.0
async-timeout==5.0.1
attrs==25.3.0
basicsr==1.4.2
bitsandbytes==0.46.0
brisque==0.0.16
Brotli @ file:///C:/b/abs_c415aux9ra/croot/brotli-split_1736182803933/work
cachetools==5.5.2
certifi==2025.4.26
cffi==1.17.1
cfgv==3.4.0
charset-normalizer==3.4.2
cloudpickle==3.1.0
colorama==0.4.6
coloredlogs==15.0.1
contourpy @ file:///C:/b/abs_f2u2o_8s9g/croot/contourpy_1732540071787/work
cycler @ file:///tmp/build/80754af9/cycler_1637851556182/work
Cython==3.1.2
datasets==3.6.0
dill==0.3.8
distlib==0.3.9
distro==1.9.0
easydict==1.13
einops==0.8.1
exceptiongroup==1.3.0
executing==2.2.0
facenet-pytorch==2.6.0
facexlib==0.3.0
filelock==3.18.0
filterpy==1.4.5
flatbuffers==25.2.10
fonttools @ file:///C:/b/abs_4crkswws2h/croot/fonttools_1737040078745/work
frozenlist==1.7.0
fsspec==2025.3.0
ftfy==6.3.1
future==1.0.0
google-ai-generativelanguage==0.6.15
google-api-core==2.25.1
google-api-python-client==2.174.0
google-auth==2.40.3
google-auth-httplib2==0.2.0
google-generativeai==0.8.5
googleapis-common-protos==1.70.0
grpcio==1.73.1
grpcio-status==1.71.0
h11==0.16.0
httpcore==1.0.9
httplib2==0.22.0
httpx==0.28.1
huggingface-hub==0.33.1
humanfriendly==10.0
icecream==2.1.5
identify==2.6.12
idna==3.10
image-quality==1.2.7
imagecodecs @ file:///D:/bld/imagecodecs_1748740296925/work
imageio @ file:///home/conda/feedstock_root/build_artifacts/imageio_1738273805233/work
imbalanced-learn==0.12.3
importlib_metadata @ file:///home/conda/feedstock_root/build_artifacts/bld/rattler-build_importlib-metadata_1747934053/work
iniconfig==2.1.0
insightface==0.7.3
jax==0.6.2
jaxlib==0.6.2
Jinja2==3.1.6
jiter==0.10.0
joblib==1.5.1
kiwisolver @ file:///C:/b/abs_faf90xet7a/croot/kiwisolver_1737040915779/work
lazy_loader @ file:///home/conda/feedstock_root/build_artifacts/lazy-loader_1733636780672/work
libsvm==3.23.0.4
libsvm-official==3.31.0
llvmlite==0.43.0
lmdb==1.6.2
lpips==0.1.4
Markdown==3.8.2
MarkupSafe==3.0.2
matplotlib==3.10.0
mediapipe==0.10.21
ml_dtypes==0.5.1
mpmath==1.3.0
multidict==6.4.4
multiprocess==0.70.16
networkx @ file:///home/conda/feedstock_root/build_artifacts/bld/rattler-build_networkx_1731521053/work
niqe==0.1.1
nodeenv==1.9.1
numba==0.60.0
numpy==1.26.4
onnx==1.18.0
onnxruntime==1.22.0
openai==0.28.0
openai-clip==1.0.1
opencv-contrib-python==4.11.0.86
opencv-python==4.11.0
opencv-python-headless==4.11.0
opt_einsum==3.4.0
packaging @ file:///C:/b/abs_3by6s2fa66/croot/packaging_1734472138782/work
pandas==2.3.0
pillow==10.2.0
piq==0.8.0
platformdirs==4.3.8
pluggy==1.6.0
ply==3.11
pre_commit==4.2.0
prettytable==3.16.0
propcache==0.3.2
proto-plus==1.26.1
protobuf==5.29.5
psutil==7.0.0
pyarrow==20.0.0
pyasn1==0.6.1
pyasn1_modules==0.4.2
pycparser==2.22
pydantic==2.11.5
pydantic_core==2.33.2
Pygments==2.19.2
pyiqa==0.1.14.1
pyparsing @ file:///C:/b/abs_40z8gyj9wi/croot/pyparsing_1731445739241/work
PyQt5==5.15.10
PyQt5_sip @ file:///C:/b/abs_d1i1jr9fgt/croot/pyqt-split_1736540551157/work/pyqt_sip
pyreadline3==3.5.4
pytest==8.4.1
python-dateutil @ file:///C:/b/abs_3au_koqnbs/croot/python-dateutil_1716495777160/work
pytz==2025.2
PyWavelets==1.8.0
PyYAML==6.0.2
regex==2024.11.6
requests==2.32.4
rsa==4.9.1
ruff==0.12.1
safetensors==0.5.3
scikit-image @ file:///D:/bld/scikit-image_1747532658763/work
scikit-learn==1.7.0
scipy @ file:///C:/bld/scipy-split_1739790833536/work/dist/scipy-1.15.2-cp310-cp310-win_amd64.whl#sha256=4748853a0c723cda1fa2bdead847ba7c2443bde9cec3436e3e7243cfa54b55ff
sentencepiece==0.2.0
sewar==0.4.6
shap==0.46.0
simsimd==6.4.9
sip @ file:///C:/b/abs_b6twfwtueg/croot/sip_1736544693649/work
six @ file:///C:/b/abs_149wuyuo1o/croot/six_1744271521515/work
slicer==0.0.8
sniffio==1.3.1
sounddevice==0.5.2
stringzilla==3.12.5
sympy==1.14.0
tb-nightly==2.20.0a20250630
tenacity==9.1.2
tensorboard==2.19.0
tensorboard-data-server==0.7.2
threadpoolctl==3.6.0
tifffile @ file:///home/conda/feedstock_root/build_artifacts/tifffile_1746986532758/work
timm==1.0.16
tokenizers==0.15.2
tomli @ file:///C:/Windows/TEMP/abs_ac109f85-a7b3-4b4d-bcfd-52622eceddf0hy332ojo/croots/recipe/tomli_1657175513137/work
torch==2.2.2
torchvision==0.17.2
tornado @ file:///C:/b/abs_7dzpc171lf/croot/tornado_1748956950306/work
tqdm==4.67.1
transformers==4.37.2
typing-inspection==0.4.1
typing_extensions==4.14.0
tzdata==2025.2
unicodedata2 @ file:///C:/b/abs_dfnftvxi4k/croot/unicodedata2_1736543771112/work
uritemplate==4.2.0
urllib3==2.4.0
virtualenv==20.31.2
wcwidth==0.2.13
Werkzeug==3.1.3
xxhash==3.5.0
yapf==0.43.0
yarl==1.20.1
zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1749421620841/work
